export const ButtonNumbers = [
  { value:"0", title:"Nothing", text:"Button that does nothing." },
  { value:"100", title:"ZeroX", text:"Zeros the X axis position." },
  { value:"101", title:"ZeroY", text:"Zeros the Y axis position." },
  { value:"102", title:"ZeroZ", text:"Zeros the Z axis position." },
  { value:"103", title:"ZeroA", text:"Zeros the A axis position." },
  { value:"104", title:"ZeroB", text:"Zeros the B axis position." },
  { value:"105", title:"ZeroC", text:"Zeros the C axis position." },
  { value:"106", title:"ZeroAll", text:"Zeros All axis position." },
  { value:"107", title:"HomeX", text:"Runs the X axis to the home sensor." },
  { value:"108", title:"HomeY", text:"Runs the Y axis to the home sensor." },
  { value:"109", title:"HomeZ", text:"Runs the Z axis to the home sensor." },
  { value:"110", title:"HomeA", text:"Runs the A axis to the home sensor." },
  { value:"111", title:"HomeB", text:"Runs the B axis to the home sensor." },
  { value:"112", title:"HomeC", text:"Runs the C axis to the home sensor." },
  { value:"113", title:"HomeAll", text:"Runs all axis to the home sensor. The homing sequence is defined in the setup." },
  { value:"114", title:"M3toggle", text:"Toggles the M3 spindle CW button." },
  { value:"115", title:"M4toggle", text:"Toggles the M4 spindle CCW button." },
  { value:"116", title:"M7toggle", text:"Toggles the M7 mist button." },
  { value:"117", title:"M8toggle", text:"Toggles the M8 flood button." },
  { value:"118", title:"G54select", text:"Selects the G54 coordinate offset." },
  { value:"119", title:"G55select", text:"Selects the G55 coordinate offset." },
  { value:"120", title:"G56select", text:"Selects the G56 coordinate offset." },
  { value:"121", title:"G57select", text:"Selects the G57 coordinate offset." },
  { value:"122", title:"G58select", text:"Selects the G58 coordinate offset." },
  { value:"123", title:"G59select", text:"Selects the G59 coordinate offset." },
  { value:"124", title:"OpenGcodefile", text:"Starts an Open G-code file dialog." },
  { value:"125", title:"CloseGcodefile", text:"Closes the G-code fájl which is loaded." },
  { value:"126", title:"EditGcodefile", text:"Opens the notepad to edit the loaded G-code file." },
  { value:"127", title:"RewindGcodefile", text:"Rewinds the loaded G-code file with jumping to the first row in the file." },
  { value:"128", title:"Cyclestart", text:"Makes a cyclic run on the loaded G-code file." },
  { value:"129", title:"Runsingleline", text:"Executes one line of code (the actual code line) of the loaded G-code file." },
  { value:"130", title:"Cyclestop", text:"Stops the G-code execution." },
  { value:"131", title:"Gotozero", text:"Moves all axis to the zero position with a rapid linear interpolation movement.(Programmed in the M204 macro file.)" },
  { value:"132", title:"FROincrease", text:"Increases the Feedrate override value." },
  { value:"133", title:"FROdecrease", text:"Decreases the Feedrate override value." },
  { value:"134", title:"SROincrease", text:"Increases the spindle speed override value." },
  { value:"135", title:"SROdecrease", text:"Decreases the spindle speed override value." },
  { value:"136", title:"Toolpathzoomin", text:"Zooms in the toolpath viewer." },
  { value:"137", title:"Toolpathzoomout", text:"Zooms out the toolpath viewer." },
  { value:"138", title:"Toolpathzoomcontents", text:"Zooms the contents in the toolpath viewer." },
  { value:"139", title:"Toolpathview45", text:"Sets the toolpath to a 45° look viewing mode." },
  { value:"140", title:"Toolpathviewright", text:"Sets the toolpath to a right side look viewing mode." },
  { value:"141", title:"Toolpathviewleft", text:"Sets the toolpath to a left side look viewing mode." },
  { value:"142", title:"Toolpathviewtop", text:"Sets the toolpath to a top side look viewing mode." },
  { value:"143", title:"ToolpathviewISO", text:"Sets the toolpath to Isometric viewing mode." },
  { value:"144", title:"Resettoggle", text:"Toggles the reset button." },
  { value:"145", title:"Offlinetoggle", text:"Toggles the offline button." },
  { value:"146", title:"Limitsoverridetoggle", text:"Toggles the limits override button." },
  { value:"147", title:"JogX+", text:"Jogs the X axis to positive direction." },
  { value:"148", title:"JogX-", text:"Jogs the X axis to negative direction." },
  { value:"149", title:"JogY+", text:"Jogs the Y axis to positive direction." },
  { value:"150", title:"JogY-", text:"Jogs the Y axis to negative direction." },
  { value:"151", title:"JogZ+", text:"Jogs the Z axis to positive direction." },
  { value:"152", title:"JogZ-", text:"Jogs the Z axis to negative direction." },
  { value:"153", title:"JogA+", text:"Jogs the A axis to positive direction." },
  { value:"154", title:"JogA-", text:"Jogs the A axis to negative direction." },
  { value:"155", title:"JogB+", text:"Jogs the B axis to positive direction." },
  { value:"156", title:"JogB-", text:"Jogs the B axis to negative direction." },
  { value:"157", title:"JogC+", text:"Jogs the C axis to positive direction." },
  { value:"158", title:"JogC-", text:"Jogs the C axis to negative direction." },
  { value:"159", title:"Jograteincrease", text:"Increases the jog rate." },
  { value:"160", title:"Jogratedecrease", text:"Decreases the jog rate." },
  { value:"161", title:"Jogmodecont", text:"Sets the jog mode to continous." },
  { value:"162", title:"Jogmodestep", text:"Sets the jog mode to stepping." },
  { value:"164", title:"Jogsteprate001", text:"Sets the jog distance when stepping mode to 0.01 Units." },
  { value:"165", title:"Jogsteprate010", text:"Sets the jog distance when stepping mode to 0.10 Units." },
  { value:"166", title:"Jogsteprate100", text:"Sets the jog distance when stepping mode to 1.00 Units." },
  { value:"167", title:"Savesettings", text:"Saves all settings to the profile file." },
  { value:"168", title:"Applysettings", text:"Applies the settings on the setup screens." },
  { value:"169", title:"Setnextline", text:"Sets the G-code execution pointer to the line defined on the screen in the 128. labelfield." },
  { value:"170", title:"G54offsetcurrentpos", text:"Offsets the actual position of the G54 coordinate system." },
  { value:"171", title:"G55offsetcurrentpos", text:"Offsets the actual position of the G55 coordinate system." },
  { value:"172", title:"G56offsetcurrentpos", text:"Offsets the actual position of the G56 coordinate system." },
  { value:"173", title:"G57offsetcurrentpos", text:"Offsets the actual position of the G57 coordinate system." },
  { value:"174", title:"G58offsetcurrentpos", text:"Offsets the actual position of the G58 coordinate system." },
  { value:"175", title:"G59offsetcurrentpos", text:"Offsets the actual position of the G59 coordinate system." },
  { value:"176", title:"G54offsetclear", text:"Clears the offset in the G54 coordinate system." },
  { value:"177", title:"G55offsetclear", text:"Clears the offset in the G55 coordinate system." },
  { value:"178", title:"G56offsetclear", text:"Clears the offset in the G56 coordinate system." },
  { value:"179", title:"G57offsetclear", text:"Clears the offset in the G57 coordinate system." },
  { value:"180", title:"G58offsetclear", text:"Clears the offset in the G58 coordinate system." },
  { value:"181", title:"G59offsetclear", text:"Clears the offset in the G59 coordinate system." },
  { value:"182", title:"Tooloffsetclear", text:"Clears the tool offset." },
  { value:"183", title:"Tooloffsetclear", text:"Clears the tool offset." },
  { value:"184", title:"Tooloffsetclear", text:"Clears the tool offset." },
  { value:"185", title:"Tooloffsetclear", text:"Clears the tool offset." },
  { value:"186", title:"Tooloffsetclear", text:"Clears the tool offset." },
  { value:"187", title:"Tooloffsetclear", text:"Clears the tool offset." },
  { value:"188", title:"Listprofiles", text:"Lists the available profile file names in the 1.Listcomponent." },
  { value:"189", title:"Deleteprofile", text:"Deletes the actually selected profile file." },
  { value:"190", title:"Loadprofile", text:"Loads the actually selected profile file." },
  { value:"191", title:"Createnewprofile", text:"Create a new profile, the name of the profile is held in the 216.inputfield." },
  { value:"192", title:"DoXMLimport", text:"Imports a Mach3 .xml setup file. The function start an open file dialog." },
  { value:"193", title:"Gotoparkposition1", text:"Commands the machine to park position 1. (Code executed in Macro M200)" },
  { value:"194", title:"Gotoparkposition2", text:"Commands the machine to park position 2. (Code executed in Macro M201)" },
  { value:"195", title:"Gotoparkposition3", text:"Commands the machine to park position 3. (Code executed in Macro M202)" },
  { value:"196", title:"Toollengthmeasurement", text:"Commands a tool length measurement. (Code executed in Macro M31)" },
  { value:"197", title:"Machinecoordstoggle", text:"Toggles the position DROs between the machine coordinates and the actual offset coordinates view." },
  { value:"198", title:"CalibrateX", text:"Calibrates the steps per units value with travel measurement for the X-axis." },
  { value:"199", title:"CalibrateY", text:"Calibrates the steps per units value with travel measurement for the Y-axis." },
  { value:"200", title:"CalibrateZ", text:"Calibrates the steps per units value with travel measurement for the Z-axis." },
  { value:"201", title:"CalibrateA", text:"Calibrates the steps per units value with travel measurement for the A-axis." },
  { value:"202", title:"CalibrateB", text:"Calibrates the steps per units value with travel measurement for the B-axis." },
  { value:"203", title:"CalibrateC", text:"Calibrates the steps per units value with travel measurement for the C-axis." },
  { value:"204", title:"Softlimitstoggle", text:"Toggles the software limits enable function." },
  { value:"205", title:"THCtoggle", text:"Toggles the THC control enable function." },
  { value:"216", title:"GotoSafeZ", text:"Moves the Z axis to SafeZ height. (Programmed in the M216 macro file.)" },
  { value:"218", title:"Zeroworktimer", text:"Zeros the work timer." },
  { value:"219", title:"ClearG92offset", text:"Clears the G92 offset coordinates." },
  { value:"220", title:"MPGXaxisselect", text:"Selects the X axis for the MPG jog." },
  { value:"221", title:"MPGYaxisselect", text:"Selects the Y axis for the MPG jog." },
  { value:"222", title:"MPGZaxisselect", text:"Selects the Z axis for the MPG jog." },
  { value:"223", title:"MPGAaxisselect", text:"Selects the A axis for the MPG jog." },
  { value:"224", title:"MPGBaxisselect", text:"Selects the B axis for the MPG jog." },
  { value:"225", title:"MPGCaxisselect", text:"Selects the C axis for the MPG jog." },
  { value:"226", title:"MPGcontmodeselect", text:"Selects the continous jog mode for the MPG." },
  { value:"227", title:"MPGsinglemodeselect", text:"Selects the single step  jog mode for the MPG." },
  { value:"228", title:"MPGmultimodeselect", text:"Selects the multi step jog mode for the MPG." },
  { value:"229", title:"JogXplusoff", text:"Switches the X axis positive direction jogging off." },
  { value:"230", title:"JogXminusoff", text:"Switches the X axis negative direction jogging off." },
  { value:"231", title:"JogYplusoff", text:"Switches the Y axis positive direction jogging off." },
  { value:"232", title:"JogYminusoff", text:"Switches the Y axis negative direction jogging off." },
  { value:"233", title:"JogZplusoff", text:"Switches the Z axis positive direction jogging off." },
  { value:"234", title:"JogZminusoff", text:"Switches the Z axis negative direction jogging off." },
  { value:"235", title:"JogAplusoff", text:"Switches the A axis positive direction jogging off." },
  { value:"236", title:"JogAminusoff", text:"Switches the A axis negative direction jogging off." },
  { value:"237", title:"JogBplusoff", text:"Switches the B axis positive direction jogging off." },
  { value:"238", title:"JogBminusoff", text:"Switches the B axis negative direction jogging off." },
  { value:"239", title:"JogCplusoff", text:"Switches the C axis positive direction jogging off." },
  { value:"240", title:"JogCminusoff", text:"Switches the C axis negative direction jogging off." },
  { value:"241", title:"Jogsteprate0001", text:"Sets the jog distance when stepping mode to 0.001 Units." },
  { value:"242-292", title:"Sethotkeycodes1to48", text:"Opens the Hotkeys keyboard key selection window." },
  { value:"293-343", title:"Sethotkeyfunctions1to48", text:"Opens a Function selection window for the hotkeys." },
  { value:"344-394", title:"Setinputtriggerfunctions1to48", text:"Opens a Function selection window for the input triggers." },
  { value:"400-449", title:"SelectTABlayer1to48", text:"Selects the TAB layer on the screen. The layer number selected is the function code - 400, so TAB layer 1. selected with code 401. Note: To select a sub layer with a hotkey or with an input trigger configure the same key or pin to select all of it's parent layers and also the layer itself, so the parent layers and the sub layers will also be selected and the sub layer will always showup this way, no matter which parent layer was originally shown." },
  { value:"450-500", title:"SetoutputtriggerLEDs1to48", text:"Opens a LED selection window for the output triggers." },
  { value:"501", title:"CAM_ImportDXF", text:"Imports a dxf drawing file to UCCAM." },
  { value:"502", title:"CAM_Generatetoolpath", text:"Generates the toolpath in UCCAM." },
  { value:"503", title:"CAM_Generategcode", text:"Creates the gcode in UCCAM." },
  { value:"504", title:"M3on", text:"Switches the M3 spindle CW button on." },
  { value:"505", title:"M3off", text:"Switches the M3 spindle CW button off." },
  { value:"506", title:"M4on", text:"Switches the M4 spindle CCW button on." },
  { value:"507", title:"M4off", text:"Switches the M4 spindle CCW button off." },
  { value:"508", title:"M7on", text:"Switches the M7 mist button on." },
  { value:"509", title:"M7off", text:"Switches the M7 mist button off." },
  { value:"510", title:"M8on", text:"Switches the M8 flood button on." },
  { value:"511", title:"M8off", text:"Switches the M8 flood button off." },
  { value:"512", title:"Reseton", text:"Switches the Reset button on." },
  { value:"513", title:"Resetoff", text:"Switches the Reset button off." },
  { value:"514", title:"Offlineon", text:"Switches the Offline button on." },
  { value:"515", title:"Offlineoff", text:"Switches the Offline button off." },
  { value:"516", title:"Machinecoordson", text:"Switches the machine coordinates button on." },
  { value:"517", title:"Machinecoordsoff", text:"Switches the machine coordinates button off." },
  { value:"518", title:"Softlimitson", text:"Switches the softlimits setting on." },
  { value:"519", title:"Softlimitsoff", text:"Switches the softlimits setting off." },
  { value:"520", title:"THCon", text:"Switches the THC control on." },
  { value:"521", title:"THCoff", text:"Switches the THC control off." },
  { value:"522", title:"Feedholdtoggle", text:"Toggles the feedhold button." },
  { value:"523", title:"Feedholdon", text:"Switches the feedhold button on." },
  { value:"524", title:"Feedholdoff", text:"Switches the feedhold button off." },
  { value:"525", title:"Configplugins", text:"Opens the plugin configuration window" },
  { value:"526", title:"Editscreen", text:"Enters the screen editor mode" },
  { value:"527", title:"Savealloffsets", text:"Saves all offset values to the profile file." },
  { value:"528", title:"Clearstatusmessages", text:"Clears the Status message box" },
  { value:"529", title:"THCAntiDiveon", text:"Switches the Anti Dive function for the THC on." },
  { value:"530", title:"THCAntiDiveoff", text:"Switches the Anti Dive function for the THC off." },
  { value:"531", title:"THCAntiDivetoggle", text:"Toggles the Anti Dive function for the THC." },
  { value:"532", title:"Configmacroloops", text:"Opens the macroloop configuration window." },
  { value:"533", title:"THCDelayon", text:"Switches the THC Delay function for the THC on." },
  { value:"534", title:"THCDelayoff", text:"Switches the THC Delay function for the THC off." },
  { value:"535", title:"THCDelaytoggle", text:"Toggles the Delay function for the THC." },
  { value:"536", title:"THCarconsignalon_emulation", text:"Switches the THC arcon virtual signal on. Can be used to emulate the THC arcon signal from keyboard." },
  { value:"537", title:"THCarconsignaloff_emulation", text:"Switches the THC arcon virtual signal off. Can be used to emulate the THC arcon signal from keyboard." },
  { value:"538", title:"THCupsignalon_emulation", text:"Switches the THC up virtual signal on. Can be used to emulate the THC up signal from keyboard." },
  { value:"539", title:"THCupsignaloff_emulation", text:"Switches the THC up virtual signal off. Can be used to emulate the THC up signal from keyboard." },
  { value:"540", title:"THCdownsignalon_emulation", text:"Switches the THC down virtual signal on. Can be used to emulate the THC down signal from keyboard." },
  { value:"541", title:"THCdownsignaloff_emulation", text:"Switches the THC down virtual signal off. Can be used to emulate the THC down signal from keyboard." },
  { value:"542", title:"THCAntiDownon", text:"Switches the Anti Down function for the THC on." },
  { value:"543", title:"THCAntiDownoff", text:"Switches the Anti Down function for the THC off." },
  { value:"544", title:"THCAntiDowntoggle", text:"Toggles the Anti Down function for the THC." },
  { value:"545", title:"Safeprobemodeon", text:"Switches the safe probe mode on." },
  { value:"546", title:"Safeprobemodeoff", text:"Switches the safe probe mode off." },
  { value:"547", title:"Safeprobemodetoggle", text:"Toggles the safe probe mode." },
  { value:"548", title:"Operatorlock", text:"Opens the operator lock/unlock window." },
  { value:"549", title:"Showstatistics", text:"Opens the machine statistics window." },
  { value:"550", title:"ShowSpindlepulleys", text:"Opens the Spindle pulleys selection window." },
  { value:"551", title:"Digitize_setfilename", text:"Sets the file name to save the Digitized points to." },
  { value:"552", title:"JogSafeprobemodeon", text:"Switches the jog safe probe mode on." },
  { value:"553", title:"JogSafeprobemodeoff", text:"Switches the jog safe probe mode off." },
  { value:"554", title:"JogSafeprobemodetoggle", text:"Toggles the jog safe probe mode." },
  { value:"555", title:"ReloadGcodefile", text:"Reloads the g-code file if a file is already loaded." },
  { value:"556", title:"JograteResetto100percent", text:"Resets the jog rate field to 100%." },
  { value:"557", title:"FROResetto100percent", text:"Resets the feed override to 100%." },
  { value:"558", title:"SROResetto100percent", text:"Resets the spindle speed override to 100%." },
  { value:"559", title:"M1optionalstopon", text:"Switches the M1 optional stop on." },
  { value:"560", title:"M1optionalstopoff", text:"Switches the M1 optional stop off." },
  { value:"561", title:"M1optionalstoptoggle", text:"Toggles the M1 optional stop state." },
  { value:"562-612", title:"Sethotkeycodes49to96", text:"Opens the Hotkeys keyboard key selection window." },
  { value:"613-663", title:"Sethotkeyfunctions49to96", text:"Opens a Function selection window for the hotkeys." },
  { value:"664-714", title:"Setinputtriggerfunctions49to96", text:"Opens a Function selection window for the input triggers." },
  { value:"715-762", title:"SetoutputtriggerLEDs49to96", text:"Opens a LED selection window for the output triggers." },
  { value:"770", title:"JogpanelShow", text:"Shows the jog panel." },
  { value:"771", title:"JogpanelHide", text:"Hides the jog panel." },
  { value:"772", title:"JogpanelToggle", text:"Toggles the jog panel visibility state." },
  { value:"773", title:"OpenSpindlePIDsetup", text:"Opens the Spindle PID controller setup window." },
  { value:"774", title:"ToolpathTCPfollowOn", text:"Locks the toolpath center to the TCP point." },
  { value:"775", title:"ToolpathTCPfollowOff", text:"Unlocks the toolpath center to the TCP point." },
  { value:"776", title:"ToolpathTCPfollowToggle", text:"Toggles the TCP follow mode." },
  { value:"777", title:"ShowToolpathZplatesetup", text:"Shows the toolpathZplate setup window." },
  { value:"778", title:"ShowCutterRcompwarnings", text:"Shows the Cutter radius compensation warnings window." },
  { value:"779", title:"OpenTooltabledetails", text:"Opens the detailed tooltable window." },
  { value:"780", title:"Savetooltabledatas", text:"Saves all the datas of the tool table to file." },
  { value:"781", title:"DereferenceAllHomes", text:"Clears the homed state of all home buttons." },
  { value:"782", title:"CloseResetandQuestionForms", text:"Closes the Reset warning and the Question forms if any of them is active." },
  { value:"783", title:"ChangetoolM6", text:"Executes the tool changing process." },
  { value:"784", title:"Toggletoolpathdimensionsvisibility", text:"Toggles the dimensions drawings visibility in the toolpath view." },
  { value:"785", title:"Toolpathdimensionsvisibilityon", text:"Switches on the dimensions drawings visibility in the toolpath view." },
  { value:"786", title:"Toolpathdimensionsvisibilityoff", text:"Switches off the dimensions drawings visibility in the toolpath view." },
  { value:"787", title:"SelectScreenset", text:"Opens the screenset selector window." },
  { value:"788", title:"Camerareloadcapturedevicelist", text:"Reloads the available camera list into listbox#3." },
  { value:"789", title:"Cameracapturetoggle", text:"Toggles the camera video capture on/off." },
  { value:"790", title:"Cameracaptureon", text:"Switches the camera video capture on." },
  { value:"791", title:"Cameracaptureoff", text:"Switches the camera video capture off." },
  { value:"792", title:"Movecameraoffset", text:"Moves the XY axes with the defined camera offset distance." },
  { value:"793", title:"Cameragrayscalefiltertoggle", text:"Toggles the camera grayscale filter on/off." },
  { value:"794", title:"Cameragrayscalefilteron", text:"Switches the camera grayscale filter on." },
  { value:"795", title:"Cameragrayscalefilteroff", text:"Switches the camera grayscale filter off." },
  { value:"796", title:"Cameraedgefiltertoggle", text:"Toggles the camera edge filter on/off." },
  { value:"797", title:"Cameraedgefilteron", text:"Switches the camera edge filter on." },
  { value:"798", title:"Cameraedgefilteroff", text:"Switches the camera edge filter off." },
  { value:"800", title:"ProbeToolQuickJump", text:"Jumps to the probe screen and selects tool probe" },
  { value:"801", title:"ToolProbeMode", text:"Selects tool probe mode" },
  { value:"802", title:"SimpleProbeMode", text:"Selects simple probe mode" },
  { value:"803", title:"AngleProbeMode", text:"Selects angle probe mode" },
  { value:"804", title:"PocketProbeMode", text:"Selects pocket probe mode" },
  { value:"805", title:"OuterProbeMode", text:"Selects outer probe mode" },
  { value:"806", title:"InnerCornerProbeMode", text:"Selects inner corner probe mode" },
  { value:"807", title:"OuterCornerProbeMode", text:"Selects outer corner probe mode" },
  { value:"808", title:"RectangleInnerProbeMode", text:"Selects rectangle inner probe mode" },
  { value:"809", title:"CircleInnerProbeMode", text:"Selects circle inner probe mode" },
  { value:"810", title:"RectangleOuterProbeMode", text:"Selects rectangle outer probe mode" },
  { value:"811", title:"CircleOuterProbeMode", text:"Selects circle outer probe mode" },
  { value:"813", title:"InnerCornerBottomLeft", text:"Selects bottom left corner for inner corner probe" },
  { value:"814", title:"InnerCornerBottomRight", text:"Selects bottom right corner for inner corner probe" },
  { value:"815", title:"InnerCornerTopRight", text:"Selects top right corner for inner corner probe" },
  { value:"816", title:"InnerCornerTopLeft", text:"Selects top left corner for inner corner probe" },
  { value:"817", title:"OuterCornerBottomLeft", text:"Selects bottom left corner for outer corner probe" },
  { value:"818", title:"OuterCornerBottomRight", text:"Selects bottom right corner for outer corner probe" },
  { value:"819", title:"OuterCornerTopRight", text:"Selects top right corner for outer corner probe" },
  { value:"820", title:"OuterCornerTopLeft", text:"Selects top left corner for outer corner probe" },
  { value:"821", title:"StartProbe", text:"Starts probing sequence or confirm probing question" },
  { value:"822", title:"ProbeAxis1SelectX", text:"Selects X axis for Axis1 on probe screen" },
  { value:"823", title:"ProbeAxis1SelectY", text:"Selects Y axis for Axis1 on probe screen" },
  { value:"824", title:"ProbeAxis1SelectZ", text:"Selects Z axis for Axis1 on probe screen" },
  { value:"825", title:"ProbeAxis1SelectA", text:"Selects A axis for Axis1 on probe screen" },
  { value:"826", title:"ProbeAxis1SelectB", text:"Selects B axis for Axis1 on probe screen" },
  { value:"827", title:"ProbeAxis1SelectC", text:"Selects C axis for Axis1 on probe screen" },
  { value:"828", title:"ProbeAxis2SelectX", text:"Selects X axis for Axis2 on probe screen" },
  { value:"829", title:"ProbeAxis2SelectY", text:"Selects Y axis for Axis2 on probe screen" },
  { value:"830", title:"ProbeAxis2SelectZ", text:"Selects Z axis for Axis2 on probe screen" },
  { value:"831", title:"ProbeAxis2SelectA", text:"Selects A axis for Axis2 on probe screen" },
  { value:"832", title:"ProbeAxis2SelectB", text:"Selects B axis for Axis2 on probe screen" },
  { value:"833", title:"ProbeAxis2SelectC", text:"Selects C axis for Axis2 on probe screen" },
  { value:"834", title:"ProbeAxisCSelectX", text:"Selects X axis for clearance axis on probe screen" },
  { value:"835", title:"ProbeAxisCSelectY", text:"Selects Y axis for clearance axis on probe screen" },
  { value:"836", title:"ProbeAxisCSelectZ", text:"Selects Z axis for clearance axis on probe screen" },
  { value:"837", title:"ProbeAxisCSelectA", text:"Selects A axis for clearance axis on probe screen" },
  { value:"838", title:"ProbeAxisCSelectB", text:"Selects B axis for clearance axis on probe screen" },
  { value:"839", title:"ProbeAxisCSelectC", text:"Selects C axis for clearance axis on probe screen" },
  { value:"840", title:"TouchToolProbeMode", text:"Selects touch probe as tool probe mode" },
  { value:"841", title:"MobileToolProbeMode", text:"Selects mobile probe as tool probe mode" },
  { value:"842", title:"FixedToolProbeMode", text:"Selects fixed probe as tool probe mode" },
  { value:"843", title:"SetAsWpProbePos", text:"Sets current position as workpiece probe position" },
  { value:"844", title:"ProbeInWpProbePos", text:"Toggles probe in workpiece probe position" },
  { value:"845", title:"GotoWpProbePos", text:"Moves to workpiece probe position" },
  { value:"846", title:"SetAsMobileProbePos", text:"Sets current position as mobile probe position" },
  { value:"847", title:"SetAsFixedProbePos", text:"Sets current position as fixed probe position" },
  { value:"848", title:"GotoProbePos", text:"Moves to mobile or fixed probe position" },
  { value:"849", title:"RefCurrentAsWp", text:"References current position as workpiece zero position" },
  { value:"850", title:"RefProbeAsWp", text:"Probes and references the probed position as workpiece zero position" },
  { value:"851", title:"ZeroProbedAxis", text:"Toggles zero probed axis" },
  { value:"852", title:"ZeroOnAllOffsets", text:"Toggles zero on all offsets" },
  { value:"853", title:"SingleProbeMode", text:"Toggles single probe mode" },
  { value:"854", title:"EnableRetract", text:"Toggles enable retract" },
  { value:"855", title:"PauseBeforeProbe", text:"Toggles pause before probe" },
  { value:"856", title:"CommonAxisSettings", text:"Toggles common axis settings" },
  { value:"857", title:"ProbeInfo", text:"Show probe screen help" },
  { value:"858", title:"GotoRef", text:"Moves axes to reference coordinates" },
  { value:"859", title:"Axis1CountGage", text:"Toggles axis 1 count gage" },
  { value:"860", title:"Axis1CountDia", text:"Toggles axis 1 count dia" },
  { value:"861", title:"Axis2CountGage", text:"Toggles axis 2 count gage" },
  { value:"862", title:"Axis2CountDia", text:"Toggles axis 2 count dia" },
  { value:"863", title:"MobileProbePosAEna", text:"Toggles mobile probe position A axis enable" },
  { value:"864", title:"MobileProbePosBEna", text:"Toggles mobile probe position B axis enable" },
  { value:"865", title:"MobileProbePosCEna", text:"Toggles mobile probe position C axis enable" },
  { value:"866", title:"FixedProbePosAEna", text:"Toggles fixed probe position A axis enable" },
  { value:"867", title:"FixedProbePosBEna", text:"Toggles fixed probe position B axis enable" },
  { value:"868", title:"FixedProbePosCEna", text:"Toggles fixed probe position C axis enable" },
  { value:"869", title:"SafeXPositive", text:"Toggles greater X is safer in G19" },
  { value:"870", title:"SafeYPositive", text:"Toggles greater Y is safer in G18" },
  { value:"871", title:"SafeZPositive", text:"Toggles greater Z is safer in G17" },
  { value:"872", title:"SaveMobileProbePos", text:"Toggles save mobile probe position on exit" },
  { value:"873", title:"SaveWpReferences", text:"Toggles save workpiece references on exit" },
  { value:"874", title:"OverrideProbeDia", text:"Toggles override probe diameter" },
  { value:"875", title:"LimitTraverseSpeed", text:"Toggles limit traverse speed" },
  { value:"876", title:"SeparateSettingsPerMode", text:"Toggles separate settings per mode" },
  { value:"877", title:"NoBlower", text:"Disables blower" },
  { value:"878", title:"BlowWithM7", text:"Sets blower to use M7" },
  { value:"879", title:"BlowWithM8", text:"Sets blower to use M8" },
  { value:"880", title:"BlowUsingOutput", text:"Sets blower to use output" },
  { value:"881", title:"BlowerPinActiveLow", text:"Toggles blower output pin active low" },
  { value:"882", title:"BlowToolProbes", text:"Sets blower to blow only on tool probes" },
  { value:"883", title:"BlowAllProbes", text:"Sets blower to blow on all probes" },
  { value:"884", title:"AirBlower", text:"Starts the blower and is on while blowing" },
  { value:"1000", title:"Increasecameratargetcircles", text:"Increases the number of camera target circles" },
  { value:"1001", title:"Decreasecameratargetcircles", text:"Decreases the number of camera target circles" },
  { value:"1002", title:"Cameratargetlinetoggle", text:"Toggles the camera target line visibility" },
  { value:"1003", title:"Cameratargetlineon", text:"Makes the camera target line visible." },
  { value:"1004", title:"Cameratargetlineoff", text:"Makes the camera target line invisible." },
  { value:"1005", title:"MovetocameraZheight", text:"Makes the Z axis to move the the set camera height." },
  { value:"1006", title:"Camerainvertimagetoggle", text:"Makes the camera image colors invertion function to toggle." },
  { value:"1007", title:"Camerainvertimageon", text:"Makes the camera image colors invertion on." },
  { value:"1008", title:"Camerainvertimageoff", text:"Makes the camera image colors invertion off." },
  { value:"20000-21999", title:"Macro_call_buttons", text:"These buttons codes call the same number of macros." },
]