export const FontsList = [
  { value:"Arial", title:"Arial" },
  { value:"Bahnschrift", title:"Bahnschrift" },
  { value:"Calibri", title:"Calibri" },
  { value:"Cambria", title:"Cambria" },
  { value:"Cambria Math", title:"Cambria Math" },
  { value:"Candara", title:"Candara" },
  { value:"Comic Sans MS", title:"Comic Sans MS" },
  { value:"Consolas", title:"Consolas" },
  { value:"Constantia", title:"Constantia" },
  { value:"Corbel", title:"Corbel" },
  { value:"Courier New", title:"Courier New" },
  { value:"Ebrima", title:"Ebrima" },
  { value:"Franklin Gothic Medium", title:"Franklin Gothic Medium" },
  { value:"Gabriola", title:"Gabriola" },
  { value:"Gadugi", title:"Gadugi" },
  { value:"Georgia", title:"Georgia" },
  { value:"HoloLens MDL2 Assets", title:"HoloLens MDL2 Assets" },
  { value:"Impact", title:"Impact" },
  { value:"Ink Free", title:"Ink Free" },
  { value:"Javanese Text", title:"Javanese Text" },
  { value:"Leelawadee UI", title:"Leelawadee UI" },
  { value:"Lucida Console", title:"Lucida Console" },
  { value:"Lucida Sans Unicode", title:"Lucida Sans Unicode" },
  { value:"Malgun Gothic", title:"Malgun Gothic" },
  { value:"Marlett", title:"Marlett" },
  { value:"Microsoft Himalaya", title:"Microsoft Himalaya" },
  { value:"Microsoft JhengHei", title:"Microsoft JhengHei" },
  { value:"Microsoft New Tai Lue", title:"Microsoft New Tai Lue" },
  { value:"Microsoft PhagsPa", title:"Microsoft PhagsPa" },
  { value:"Microsoft Sans Serif", title:"Microsoft Sans Serif" },
  { value:"Microsoft Tai Le", title:"Microsoft Tai Le" },
  { value:"Microsoft YaHei", title:"Microsoft YaHei" },
  { value:"Microsoft Yi Baiti", title:"Microsoft Yi Baiti" },
  { value:"MingLiU-ExtB", title:"MingLiU-ExtB" },
  { value:"Mongolian Baiti", title:"Mongolian Baiti" },
  { value:"MS Gothic", title:"MS Gothic" },
  { value:"MV Boli", title:"MV Boli" },
  { value:"Myanmar Text", title:"Myanmar Text" },
  { value:"Nirmala UI", title:"Nirmala UI" },
  { value:"Palatino Linotype", title:"Palatino Linotype" },
  { value:"Segoe MDL2 Assets", title:"Segoe MDL2 Assets" },
  { value:"Segoe Print", title:"Segoe Print" },
  { value:"Segoe Script", title:"Segoe Script" },
  { value:"Segoe UI", title:"Segoe UI" },
  { value:"Segoe UI Emoji", title:"Segoe UI Emoji" },
  { value:"Segoe UI Historic", title:"Segoe UI Historic" },
  { value:"Segoe UI Symbol", title:"Segoe UI Symbol" },
  { value:"SimSun", title:"SimSun" },
  { value:"Sitka", title:"Sitka" },
  { value:"Sylfaen", title:"Sylfaen" },
  { value:"Symbol", title:"Symbol" },
  { value:"Tahoma", title:"Tahoma" },
  { value:"Times New Roman", title:"Times New Roman" },
  { value:"Trebuchet MS", title:"Trebuchet MS" },
  { value:"Verdana", title:"Verdana" },
  { value:"Webdings", title:"Webdings" },
  { value:"Wingdings", title:"Wingdings" },
  { value:"Yu Gothic", title:"Yu Gothic" },
]