export const Fonts = [
  { value:"Arial", title:"Arial" },
  { value:"Calibri", title:"Calibri" },
  { value:"Cambria", title:"Cambria" },
  { value:"Candara", title:"Candara" },
  { value:"Comic Sans MS", title:"Comic Sans MS" },
  { value:"Consolas", title:"Consolas" },
  { value:"Constantia", title:"Constantia" },
  { value:"Corbel", title:"Corbel" },
  { value:"Courier New", title:"Courier New" },
  { value:"Georgia", title:"Georgia" },
  { value:"Impact", title:"Impact" },
  { value:"Lucida Console", title:"Lucida Console" },
  { value:"Lucida Sans Unicode", title:"Lucida Sans Unicode" },
  { value:"Microsoft Sans Serif", title:"Microsoft Sans Serif" },
  { value:"Palatino Linotype", title:"Palatino Linotype" },
  { value:"Segoe UI", title:"Segoe UI" },
  { value:"Tahoma", title:"Tahoma" },
  { value:"Times New Roman", title:"Times New Roman" },
  { value:"Trebuchet MS", title:"Trebuchet MS" },
  { value:"Verdana", title:"Verdana" },
];
