export const LedNumbers = [
  { value:"1", title:"OutputPT1PN1", text:"Indicates the actual logic state of port#1 pin#1." },
  { value:"2", title:"OutputPT1PN2", text:"Indicates the actual logic state of port#1 pin#2." },
  { value:"3", title:"OutputPT1PN3", text:"Indicates the actual logic state of port#1 pin#3." },
  { value:"4", title:"OutputPT1PN4", text:"Indicates the actual logic state of port#1 pin#4." },
  { value:"5", title:"OutputPT1PN5", text:"Indicates the actual logic state of port#1 pin#5." },
  { value:"6", title:"OutputPT1PN6", text:"Indicates the actual logic state of port#1 pin#6." },
  { value:"7", title:"OutputPT1PN7", text:"Indicates the actual logic state of port#1 pin#7." },
  { value:"8", title:"OutputPT1PN8", text:"Indicates the actual logic state of port#1 pin#8." },
  { value:"9", title:"OutputPT1PN9", text:"Indicates the actual logic state of port#1 pin#9." },
  { value:"10", title:"OutputPT1PN10", text:"Indicates the actual logic state of port#1 pin#10." },
  { value:"11", title:"OutputPT1PN11", text:"Indicates the actual logic state of port#1 pin#11." },
  { value:"12", title:"OutputPT1PN12", text:"Indicates the actual logic state of port#1 pin#12." },
  { value:"13", title:"OutputPT1PN13", text:"Indicates the actual logic state of port#1 pin#13." },
  { value:"14", title:"OutputPT1PN14", text:"Indicates the actual logic state of port#1 pin#14." },
  { value:"15", title:"OutputPT1PN15", text:"Indicates the actual logic state of port#1 pin#15." },
  { value:"16", title:"OutputPT1PN16", text:"Indicates the actual logic state of port#1 pin#16." },
  { value:"17", title:"OutputPT1PN17", text:"Indicates the actual logic state of port#1 pin#17." },
  { value:"18", title:"Idle", text:"Indicates the Idle state of the device." },
  { value:"19", title:"Run", text:"Indicates a run state of the device. This is the opposite of the Idle state." },
  { value:"20", title:"Jog", text:"Active when a jog command is being executed." },
  { value:"21", title:"Dwell", text:"Indicates a dwell in progress." },
  { value:"22", title:"Backlash", text:"Active when the backlash compensation is being executed." },
  { value:"23", title:"Home", text:"Active when the homing command is being executed." },
  { value:"24", title:"Probing", text:"Active when the probing command is being executed." },
  { value:"25", title:"Reset", text:"Indicates an active reset signal." },
  { value:"26", title:"Hardlimit", text:"Active when any of the configured limit inputs are triggered." },
  { value:"27", title:"Limitsoverride", text:"Active if the limits are overriden by the user." },
  { value:"28", title:"Toolchangeinprogress", text:"Active when a tool change macro is being executed." },
  { value:"29", title:"Xlimitpositive", text:"Active when the X-axis positive side limit switch is triggered." },
  { value:"30", title:"Ylimitpositive", text:"Active when the Y-axis positive side limit switch is triggered." },
  { value:"31", title:"Zlimitpositive", text:"Active when the Z-axis positive side limit switch is triggered." },
  { value:"32", title:"Alimitpositive", text:"Active when the A-axis positive side limit switch is triggered." },
  { value:"33", title:"Blimitpositive", text:"Active when the B-axis positive side limit switch is triggered." },
  { value:"34", title:"Climitpositive", text:"Active when the C-axis positive side limit switch is triggered." },
  { value:"35", title:"Index", text:"Active when the index input is triggered." },
  { value:"36", title:"Estop", text:"Active when the estop input is triggered." },
  { value:"37", title:"Probe", text:"Active when the probe input is triggered." },
  { value:"38", title:"Xlimitnegative", text:"Active when the X-axis negative side limit switch is triggered." },
  { value:"39", title:"Ylimitnegative", text:"Active when the Y-axis negative side limit switch is triggered." },
  { value:"40", title:"Zlimitnegative", text:"Active when the Z-axis negative side limit switch is triggered." },
  { value:"41", title:"Alimitnegative", text:"Active when the A-axis negative side limit switch is triggered." },
  { value:"42", title:"Blimitnegative", text:"Active when the B-axis negative side limit switch is triggered." },
  { value:"43", title:"Climitnegative", text:"Active when the C-axis negative side limit switch is triggered." },
  { value:"44", title:"Xhome", text:"Active when then X-axis home input is triggered." },
  { value:"45", title:"Yhome", text:"Active when then Y-axis home input is triggered." },
  { value:"46", title:"Zhome", text:"Active when then Z-axis home input is triggered." },
  { value:"47", title:"Ahome", text:"Active when then A-axis home input is triggered." },
  { value:"48", title:"Bhome", text:"Active when then B-axis home input is triggered." },
  { value:"49", title:"Chome", text:"Active when then C-axis home input is triggered." },
  { value:"50", title:"SpindleCW", text:"Active when the spindle is rotating Clockwise." },
  { value:"51", title:"SpindleCCW", text:"Active when the spindle is rotating Counter-clockwise" },
  { value:"52", title:"Miston", text:"Active when the mist coolant is on." },
  { value:"53", title:"Floodon", text:"Active when the flood coolant is on." },
  { value:"54", title:"Cyclestart", text:"Active when a G-code execution cycle is in progress." },
  { value:"55", title:"Runsingleline", text:"Active when a Single line G-code execution cycle is in progress." },
  { value:"56", title:"Xhomed", text:"Active when the X-axis was already homed." },
  { value:"57", title:"Yhomed", text:"Active when the Y-axis was already homed." },
  { value:"58", title:"Zhomed", text:"Active when the Z-axis was already homed." },
  { value:"59", title:"Ahomed", text:"Active when the A-axis was already homed." },
  { value:"60", title:"Bhomed", text:"Active when the B-axis was already homed." },
  { value:"61", title:"Chomed", text:"Active when the C-axis was already homed." },
  { value:"62", title:"Machinecoords", text:"Active when the machine coordinate system is selected to view in the position DROs." },
  { value:"63", title:"THCon", text:"Active when the THC on physical input is active." },
  { value:"64", title:"THCup", text:"Active when the THC up physical input is active." },
  { value:"65", title:"THCdown", text:"Active when the THC down physical input is active." },
  { value:"66", title:"THCenabled", text:"Active when the THC control is enabled." },
  { value:"67", title:"Softlimitsenabled", text:"Active when the Software limit function is enabled." },
  { value:"68", title:"THCdelay", text:"Active when the THC delay is ongoing." },
  { value:"69", title:"OutputPT2PN1", text:"Indicates the actual logic state of port#2 pin#1." },
  { value:"70", title:"OutputPT2PN2", text:"Indicates the actual logic state of port#2 pin#2." },
  { value:"71", title:"OutputPT2PN3", text:"Indicates the actual logic state of port#2 pin#3." },
  { value:"72", title:"OutputPT2PN4", text:"Indicates the actual logic state of port#2 pin#4." },
  { value:"73", title:"OutputPT2PN5", text:"Indicates the actual logic state of port#2 pin#5." },
  { value:"74", title:"OutputPT2PN6", text:"Indicates the actual logic state of port#2 pin#6." },
  { value:"75", title:"OutputPT2PN7", text:"Indicates the actual logic state of port#2 pin#7." },
  { value:"76", title:"OutputPT2PN8", text:"Indicates the actual logic state of port#2 pin#8." },
  { value:"77", title:"OutputPT2PN9", text:"Indicates the actual logic state of port#2 pin#9." },
  { value:"78", title:"OutputPT2PN10", text:"Indicates the actual logic state of port#2 pin#10." },
  { value:"79", title:"OutputPT2PN11", text:"Indicates the actual logic state of port#2 pin#11." },
  { value:"80", title:"OutputPT2PN12", text:"Indicates the actual logic state of port#2 pin#12." },
  { value:"81", title:"OutputPT2PN13", text:"Indicates the actual logic state of port#2 pin#13." },
  { value:"82", title:"OutputPT2PN14", text:"Indicates the actual logic state of port#2 pin#14." },
  { value:"83", title:"OutputPT2PN15", text:"Indicates the actual logic state of port#2 pin#15." },
  { value:"84", title:"OutputPT2PN16", text:"Indicates the actual logic state of port#2 pin#16." },
  { value:"85", title:"OutputPT2PN17", text:"Indicates the actual logic state of port#2 pin#17." },
  { value:"86", title:"OutputPT3PN1", text:"Indicates the actual logic state of port#3 pin#1." },
  { value:"87", title:"OutputPT3PN2", text:"Indicates the actual logic state of port#3 pin#2." },
  { value:"88", title:"OutputPT3PN3", text:"Indicates the actual logic state of port#3 pin#3." },
  { value:"89", title:"OutputPT3PN4", text:"Indicates the actual logic state of port#3 pin#4." },
  { value:"90", title:"OutputPT3PN5", text:"Indicates the actual logic state of port#3 pin#5." },
  { value:"91", title:"OutputPT3PN6", text:"Indicates the actual logic state of port#3 pin#6." },
  { value:"92", title:"OutputPT3PN7", text:"Indicates the actual logic state of port#3 pin#7." },
  { value:"93", title:"OutputPT3PN8", text:"Indicates the actual logic state of port#3 pin#8." },
  { value:"94", title:"OutputPT3PN9", text:"Indicates the actual logic state of port#3 pin#9." },
  { value:"95", title:"OutputPT3PN10", text:"Indicates the actual logic state of port#3 pin#10." },
  { value:"96", title:"OutputPT3PN11", text:"Indicates the actual logic state of port#3 pin#11." },
  { value:"97", title:"OutputPT3PN12", text:"Indicates the actual logic state of port#3 pin#12." },
  { value:"98", title:"OutputPT3PN13", text:"Indicates the actual logic state of port#3 pin#13." },
  { value:"99", title:"OutputPT3PN14", text:"Indicates the actual logic state of port#3 pin#14." },
  { value:"100", title:"OutputPT3PN15", text:"Indicates the actual logic state of port#3 pin#15." },
  { value:"101", title:"OutputPT3PN16", text:"Indicates the actual logic state of port#3 pin#16." },
  { value:"102", title:"OutputPT3PN17", text:"Indicates the actual logic state of port#3 pin#17." },
  { value:"103", title:"OutputPT4PN1", text:"Indicates the actual logic state of port#4 pin#1." },
  { value:"104", title:"OutputPT4PN2", text:"Indicates the actual logic state of port#4 pin#2." },
  { value:"105", title:"OutputPT4PN3", text:"Indicates the actual logic state of port#4 pin#3." },
  { value:"106", title:"OutputPT4PN4", text:"Indicates the actual logic state of port#4 pin#4." },
  { value:"107", title:"OutputPT4PN5", text:"Indicates the actual logic state of port#4 pin#5." },
  { value:"108", title:"OutputPT4PN6", text:"Indicates the actual logic state of port#4 pin#6." },
  { value:"109", title:"OutputPT4PN7", text:"Indicates the actual logic state of port#4 pin#7." },
  { value:"110", title:"OutputPT4PN8", text:"Indicates the actual logic state of port#4 pin#8." },
  { value:"111", title:"OutputPT4PN9", text:"Indicates the actual logic state of port#4 pin#9." },
  { value:"112", title:"OutputPT4PN10", text:"Indicates the actual logic state of port#4 pin#10." },
  { value:"113", title:"OutputPT4PN11", text:"Indicates the actual logic state of port#4 pin#11." },
  { value:"114", title:"OutputPT4PN12", text:"Indicates the actual logic state of port#4 pin#12." },
  { value:"115", title:"OutputPT4PN13", text:"Indicates the actual logic state of port#4 pin#13." },
  { value:"116", title:"OutputPT4PN14", text:"Indicates the actual logic state of port#4 pin#14." },
  { value:"117", title:"OutputPT4PN15", text:"Indicates the actual logic state of port#4 pin#15." },
  { value:"118", title:"OutputPT4PN16", text:"Indicates the actual logic state of port#4 pin#16." },
  { value:"119", title:"OutputPT4PN17", text:"Indicates the actual logic state of port#4 pin#17." },
  { value:"120", title:"OutputPT5PN1", text:"Indicates the actual logic state of port#5 pin#1." },
  { value:"121", title:"OutputPT5PN2", text:"Indicates the actual logic state of port#5 pin#2." },
  { value:"122", title:"OutputPT5PN3", text:"Indicates the actual logic state of port#5 pin#3." },
  { value:"123", title:"OutputPT5PN4", text:"Indicates the actual logic state of port#5 pin#4." },
  { value:"124", title:"OutputPT5PN5", text:"Indicates the actual logic state of port#5 pin#5." },
  { value:"125", title:"OutputPT5PN6", text:"Indicates the actual logic state of port#5 pin#6." },
  { value:"126", title:"OutputPT5PN7", text:"Indicates the actual logic state of port#5 pin#7." },
  { value:"127", title:"OutputPT5PN8", text:"Indicates the actual logic state of port#5 pin#8." },
  { value:"128", title:"OutputPT5PN9", text:"Indicates the actual logic state of port#5 pin#9." },
  { value:"129", title:"OutputPT5PN10", text:"Indicates the actual logic state of port#5 pin#10." },
  { value:"130", title:"OutputPT5PN11", text:"Indicates the actual logic state of port#5 pin#11." },
  { value:"131", title:"OutputPT5PN12", text:"Indicates the actual logic state of port#5 pin#12." },
  { value:"132", title:"OutputPT5PN13", text:"Indicates the actual logic state of port#5 pin#13." },
  { value:"133", title:"OutputPT5PN14", text:"Indicates the actual logic state of port#5 pin#14." },
  { value:"134", title:"OutputPT5PN15", text:"Indicates the actual logic state of port#5 pin#15." },
  { value:"135", title:"OutputPT5PN16", text:"Indicates the actual logic state of port#5 pin#16." },
  { value:"136", title:"OutputPT5PN17", text:"Indicates the actual logic state of port#5 pin#17." },
  { value:"137", title:"MPGAPIN", text:"Indicates the logic state of the MPG A pin." },
  { value:"138", title:"MPGBPIN", text:"Indicates the logic state of the MPG B pin." },
  { value:"139", title:"EnableXaxis", text:"On when the enable output of the X axis is active" },
  { value:"140", title:"EnableYaxis", text:"On when the enable output of the Y axis is active" },
  { value:"141", title:"EnableZaxis", text:"On when the enable output of the Z axis is active" },
  { value:"142", title:"EnableAaxis", text:"On when the enable output of the A axis is active" },
  { value:"143", title:"EnableBaxis", text:"On when the enable output of the B axis is active" },
  { value:"144", title:"EnableCaxis", text:"On when the enable output of the C axis is active" },
  { value:"145", title:"Jogmodecontinous", text:"On when the continous jog mode is selected." },
  { value:"146", title:"Jogmodestep", text:"On when the step jog mode is selected." },
  { value:"148", title:"Jograte0001", text:"On when the step jog rate is set to 0.001 units." },
  { value:"149", title:"Jograte0010", text:"On when the step jog rate is set to 0.01 units." },
  { value:"150", title:"Jograte0100", text:"On when the step jog rate is set to 0.1 units." },
  { value:"151", title:"Jograte1000", text:"On when the step jog rate is set to 1 units." },
  { value:"152", title:"MPGmodecont", text:"On when the MPG continous mode is selected." },
  { value:"153", title:"MPGmodesingle", text:"On when the MPG single mode is selected." },
  { value:"154", title:"MPGmodemulti", text:"On when the MPG multi mode is selected." },
  { value:"155", title:"MPGXaxisselect", text:"On when the X axis is selected for the MPG jog." },
  { value:"156", title:"MPGYaxisselect", text:"On when the Y axis is selected for the MPG jog." },
  { value:"157", title:"MPGZaxisselect", text:"On when the Z axis is selected for the MPG jog." },
  { value:"158", title:"MPGAaxisselect", text:"On when the A axis is selected for the MPG jog." },
  { value:"159", title:"MPGBaxisselect", text:"On when the B axis is selected for the MPG jog." },
  { value:"160", title:"MPGCaxisselect", text:"On when the C axis is selected for the MPG jog." },
  { value:"161-211", title:"TABlayervisible0to50", text:"On when the tab layer is visible. The layer number selected is the LED code - 161, so the 161. LED code is for the tab layer 0. and the 211. LED code is for the 50. tab layer. Note: When more than one tab layer is visible, for example if a tab layer has a sub-tab layer which is also visible then both LED codes are active." },
  { value:"212", title:"Offlinemode", text:"On when the offline mode is active." },
  { value:"213", title:"Sync_thread", text:"Active when a syncronous thread cutting is in execution." },
  { value:"214", title:"EncoderApin", text:"Indicates the logic state of the Encoder A pin." },
  { value:"215", title:"EncoderBpin", text:"Indicates the logic state of the Encoder B pin." },
  { value:"216", title:"MDIrunning", text:"On when an MDI command is in progress." },
  { value:"217", title:"Feedhold", text:"On when the feedhold button is avtice." },
  { value:"218", title:"Isdemomode", text:"On if the software is running in demo mode." },
  { value:"219", title:"Laserdataloaded", text:"On if a laser data object is loaded to the memory for laser engraving." },
  { value:"220", title:"Laserrunning", text:"On when a laser engraving is in progress using the laser data object." },
  { value:"221", title:"OutputPT5PN26", text:"Indicates the actual logic state of port#5 pin#26. (M44 motherboard only.)" },
  { value:"222", title:"OutputPT5PN27", text:"Indicates the actual logic state of port#5 pin#27. (M44 motherboard only.)" },
  { value:"223", title:"OutputPT5PN28", text:"Indicates the actual logic state of port#5 pin#28. (M44 motherboard only.)" },
  { value:"224", title:"OutputPT5PN29", text:"Indicates the actual logic state of port#5 pin#29. (M44 motherboard only.)" },
  { value:"225", title:"OutputPT5PN30", text:"Indicates the actual logic state of port#5 pin#30. (M44 motherboard only.)" },
  { value:"226", title:"OutputPT5PN31", text:"Indicates the actual logic state of port#5 pin#31. (M44 motherboard only.)" },
  { value:"227", title:"OutputPT5PN32", text:"Indicates the actual logic state of port#5 pin#32. (M44 motherboard only.)" },
  { value:"228", title:"OutputPT5PN33", text:"Indicates the actual logic state of port#5 pin#33. (M44 motherboard only.)" },
  { value:"229", title:"M0stopactive", text:"Indicates that the M0 stop is active." },
  { value:"230", title:"M1stopactive", text:"Indicates that the M1 stop is active." },
  { value:"231", title:"M60stopactive", text:"Indicates that the M60 stop is active." },
  { value:"232", title:"Pause", text:"On when any of the M0 or M1 or M60 stop mode is active." },
  { value:"233", title:"THCAntidiveactive", text:"On when in THC control and the Anti diving happens." },
  { value:"234", title:"OutputPT1PN94", text:"Indicates the actual logic state of port#1 pin#94. (5441 motherboard only.)" },
  { value:"235", title:"OutputPT1PN95", text:"Indicates the actual logic state of port#1 pin#95. (5441 motherboard only.)" },
  { value:"236", title:"MPGJogOn", text:"Indicates that the MPG jogging is active." },
  { value:"237", title:"THCarcon_emulation", text:"Indicates that the THCarcon emulation signal is active." },
  { value:"238", title:"THCup_emulation", text:"Indicates that the THCup emulation signal is active." },
  { value:"239", title:"THCdown_emulation", text:"Indicates that the THCdown emulation signal is active." },
  { value:"240", title:"THCantidiveenabled", text:"On when the THC anti dive function is enabled." },
  { value:"241", title:"THCdelayenabled", text:"On when the THC delay function is enabled." },
  { value:"242", title:"THCantidownenabled", text:"On when the THC anti down function is enabled." },
  { value:"243", title:"SafeProbeModeactive", text:"On when the SafeProbeMode is active. The safe probe mode actives the Reset if the probe goes on when not probing." },
  { value:"244", title:"ProbedOK", text:"On if the last probing (G31) was finished with a probe touch, off if the last probing did not end with a touch." },
  { value:"245", title:"Digitizing", text:"On when the M40 digitizing command is active." },
  { value:"246", title:"JogSafeProbeModeactive", text:"On when the JogSafeProbeMode is active. The jog safe probe mode stops the jog motion if the probe goes on while jogging." },
  { value:"247", title:"M1optionalstopenabled", text:"On when the M1 optional stop is enabled" },
  { value:"248", title:"ScaleXactive", text:"On when the X axis scaling differs from value 1." },
  { value:"249", title:"ScaleYactive", text:"On when the Y axis scaling differs from value 1." },
  { value:"250", title:"ScaleZactive", text:"On when the Z axis scaling differs from value 1." },
  { value:"251", title:"ScaleAactive", text:"On when the A axis scaling differs from value 1." },
  { value:"252", title:"ScaleBactive", text:"On when the B axis scaling differs from value 1." },
  { value:"253", title:"ScaleCactive", text:"On when the C axis scaling differs from value 1." },
  { value:"254", title:"G68Rotationactive", text:"On when the G68 rotation is active." },
  { value:"255", title:"TCPfollowmodeactive", text:"On when the toolpath TCP follow mode is active." },
  { value:"256", title:"FROdisabled", text:"On if the feedrate override control (FRO) is disabled." },
  { value:"257", title:"SROdisabled", text:"On if the spindle speed override control (SRO) is disabled." },
  { value:"258", title:"FROover100", text:"On if the FRO is over 100%" },
  { value:"259", title:"FROunder100", text:"On if the FRO is under 100%" },
  { value:"260", title:"SROover100", text:"On if the SRO is over 100%" },
  { value:"261", title:"SROunder100", text:"On if the SRO is under 100%" },
  { value:"262", title:"Proberadiusdisabled", text:"On if the probe radius compensation in the digitizing settings is disabled." },
  { value:"263", title:"Rapidmovementselected", text:"Warning LED that rapid G0 code is selected." },
  { value:"264", title:"Cameracaptureon", text:"On when the camera is activated." },
  { value:"265", title:"Cameragrayscalefilteron", text:"On when the camera grayscale filter is activated." },
  { value:"266", title:"Cameraedgefilteron", text:"On when the camera edge filter is activated." },
  { value:"267", title:"Cameratargetlineon", text:"On when the camera target line is shown." },
  { value:"268", title:"Softlimitactive", text:"On if any of the machine axis reached the softlimit." },
  { value:"269", title:"Cameraimageinverton", text:"On when the camera image invertion filter is activated." },
  { value:"300", title:"ProbeError", text:"On if probe was not successful on probe screen" },
  { value:"301", title:"ProbePaused", text:"On if probe is paused or question needs to be confirmed" },
  { value:"302", title:"Axis1Disable", text:"On if Axis1 cannot be selected on probe screen" },
  { value:"303", title:"Axis2Disable", text:"On if Axis2 cannot be selected on probe screen" },
  { value:"304", title:"Axis3Disable", text:"On if AxisC cannot be selected on probe screen" },
  { value:"305", title:"TouchProbeWpCoordsSaved", text:"On if workpiece probe position is saved" },
  { value:"306", title:"MobileProbeCoordsSaved", text:"On if mobile probe position is saved" },
  { value:"307", title:"FixedProbeCoordsSaved", text:"On if fixed probe position is saved" },
  { value:"308", title:"MobileWpReferenced", text:"On if workpiece is referenced to mobile probe" },
  { value:"309", title:"FixedWpReferenced", text:"On if workpiece is referenced to fixed probe." },

]